services:
  postgres:
    image: postgres:15
    container_name: image-postgres
    environment:
      POSTGRES_USER: postgres2
      POSTGRES_PASSWORD: postgres2
      POSTGRES_DB: images
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5437:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres2 -d images"]
      interval: 2s
      timeout: 2s
      retries: 10

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    container_name: image-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.6.0
    container_name: image-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka:29092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_INTERNAL://0.0.0.0:29092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  api:
    build:
      context: .
      dockerfile: cmd/api/Dockerfile
    container_name: image-api
    depends_on:
       kafka:
        condition: service_started
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres2
      DB_PASSWORD: postgres2
      DB_NAME: images
      KAFKA_BROKER: kafka:29092
      STORAGE_DIR: /app/data
      WATERMARK_TEXT: "MyWatermark"
    ports:
      - "8087:8080"
    volumes:
      - ./data:/app/data

  worker:
    build:
      context: .
      dockerfile: cmd/worker/Dockerfile
    container_name: image-worker
    depends_on:
       kafka:
        condition: service_started
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres2
      DB_PASSWORD: postgres2
      DB_NAME: images
      KAFKA_BROKER: kafka:29092
      STORAGE_DIR: /app/data
      WATERMARK_TEXT: "MyWatermark"
    volumes:
      - ./data:/app/data

volumes:
  db_data:
